#!/bin/bash
# Configure ruby ssh authorized_keys file if available via mdata

if mdata-get forgejo_authorized_keys 1>/dev/null 2>&1; then
  home='/home/forgejo'
  mkdir -p ${home}/.ssh
  echo "# This file is managed by mdata-get ruby_authorized_keys" \
    > ${home}/.ssh/authorized_keys
  mdata-get forgejo_authorized_keys >> ${home}/.ssh/authorized_keys
  chmod 0700 ${home}/.ssh
  chmod 0640 ${home}/.ssh/authorized_keys
  chown forgejo:forgejo ${home}/.ssh/authorized_keys
fi
